name: Docker SAMBA server image CI build for PR

on:
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Docker SAMBA server image
        run: docker build -t docker-samba .
